package io.github.magisk317.mipush.common.island

/** Cross-process preference keys shared by manager, XMSF, and SystemUI hooks. */
const val ISLAND_PREF_AUTHORITY = "com.xiaomi.xmsf.island.prefs"
const val ISLAND_PREF_READ_PERMISSION = "com.xiaomi.xmsf.permission.READ_ISLAND_PREFS"
const val ISLAND_PREF_PATH_FLAGS = "flags"
const val ISLAND_PREF_COLUMN_KEY = "key"
const val ISLAND_PREF_COLUMN_VALUE = "value"
const val ISLAND_PREF_COLUMN_PACKAGE = "pkg"
const val ISLAND_PREF_COLUMN_USER = "user"
const val ISLAND_PREF_ENABLED = "pref_island_enabled"
const val ISLAND_PREF_TIMEOUT = "pref_island_timeout"
const val ISLAND_PREF_FIRST_FLOAT = "pref_island_first_float"
const val ISLAND_PREF_ENABLE_FLOAT = "pref_island_enable_float"
const val ISLAND_PREF_SHOW_NOTIFICATION = "pref_island_show_notification"
const val ISLAND_PREF_SHOW_ORIGINAL_NOTIFICATION = "pref_island_show_original_notification"
const val ISLAND_PREF_FOCUS_NOTIF = "pref_island_focus_notif"
const val COLOR_STATUS_BAR_ICON_KEY = "pref_color_status_bar_icon"
const val COLOR_STATUS_BAR_ICON_GLOBAL_KEY = "pref_color_status_bar_icon_global"
const val DUAL_APP_ENABLED_KEY = "dual_app_enabled"
const val LOG_SANITIZATION_ENABLED_KEY = "pref_log_sanitization_enabled"
