package com.xiaomi.channel.commonutils.misc

object ScheduledJobConstants {
    const val ACCOUNT_COLLECTION_JOB_ID = "7"
    const val APP_ACTIVE_COLLECTION_JOB_ID = "5"
    const val APP_IS_INSTALLED_COLLECTION_JOB_ID = "24"
    const val APP_LIST_COLLECTION_JOB_ID = "4"
    const val AWAKE_APP_PING_JOB = "22"
    const val BATTERY_COLLECTION_JOB_ID = "20"
    const val BLUETOOTH_COLLECTION_JOB_ID = "6"
    const val BROADCAST_ACTION_JOB_ID = "12"
    const val CHECK_WRITE_EVENT_JOB_ID = "100888"
    const val CHECK_WRITE_PERF_JOB_ID = "100889"
    const val DEVICE_BASE_INFO_JOB_ID = "13"
    const val DEVICE_INFO_COLLECTION_JOB_ID = "3"
    const val EVENT_UPLOAD_JOB_ID = "100886"
    const val GEO_UPDATE_LOC_JOB_ID = "11"
    const val NOTIFICATION_TIMEOUT_JOB_ID = "n_timeout_"
    const val OC_VERSION_CHECK_JOB_ID = "2"
    const val PERF_UPLOAD_JOB_ID = "100887"
    const val PUSH_CONTROL_UPDATE_JOB_ID = "16"
    const val SEND_EXEC_CMD_JOB_ID = "100957"
    const val STAT_CHECK_DB_ID = "10054"
    const val STAT_DELETE_JOB_ID = "10053"
    const val STAT_UPLOAD_JOB_ID = "10052"
    const val STORAGE_COLLECTION_JOB_ID = "23"
    const val SYNC_MIID_JOB_ID = "10"
    const val TOP_APP_COLLECTION_JOB_ID = "9"
    const val TOP_NOTIFICATION_UPDATE_JOB_ID = "n_top_update_"
    const val UPLOAD_JOB_ID = "1"
    const val UPLOAD_NOTIFICATION_INFO_JOB_ID = "17"
    const val USAGE_STATS_COLLECTION_JOB_ID = "18"
    const val WIFI_COLLECTION_JOB_ID = "8"
    const val WIFI_DEVICES_MAC_JOB_ID = "14"
}
