[templates.redmi_k90.custom_props]
"ro.fota.oem" = "Xiaomi"
"ro.rom.zone" = "1"
"ro.mi.development" = "false"
"ro.miui.ui.version.code" = "13"
"ro.miui.ui.version.name" = "V130"
"ro.miui.version.code_time" = "1625587200"
"ro.miui.build.region" = "cn"
"ro.miui.internal.storage" = "/sdcard/"
"ro.miui.cust_variant" = "cn"
"ro.miui.region" = "CN"
"ro.vendor.miui.region" = "CN"
"ro.product.locale" = "zh-CN"
"ro.product.locale.region" = "CN"
"ro.product.locale.language" = "zh"
"ro.product.country.region" = "CN"
"persist.sys.country" = "CN"
"persist.sys.oppo.region" = "__EMPTY__"
"ro.oppo.regionmark" = "__EMPTY__"
"ro.hw.country" = "__EMPTY__"
"ro.csc.countryiso_code" = "__EMPTY__"
"gsm.vivo.countrycode" = "__EMPTY__"
"persist.sys.oem.region" = "__EMPTY__"
"ro.vivo.os.version" = "__EMPTY__"
"sys.boot_completed" = "1"
"ro.product.cpu.abi" = "arm64-v8a"
"ro.product.cpu.abi2" = "armeabi-v7a"
"ro.product.cpu.abilist" = "arm64-v8a,armeabi-v7a,armeabi"
"ro.product.cpu.abilist32" = "armeabi-v7a,armeabi"
"ro.product.cpu.abilist64" = "arm64-v8a"
"ro.product.board" = "picasso"
"ro.build.id" = "SKQ1.211006.001"
"ro.build.version.incremental" = "V13.0.5.0.SGICNXM"
"ro.build.version.release" = "12"
"ro.build.version.security_patch" = "2022-02-01"
"ro.build.type" = "user"
"ro.build.user" = "builder"
"ro.build.host" = "miui-build"
"ro.build.tags" = "release-keys"
"ro.build.description" = "picasso-user 12 SKQ1.211006.001 V13.0.5.0.SGICNXM release-keys"
"ro.build.product" = "picasso"
"ro.product.property_source_order" = "odm,vendor,product,system_ext,system"
"ro.product.system.manufacturer" = "Xiaomi"
"ro.product.vendor.brand" = "Xiaomi"
"ro.product.vendor.manufacturer" = "Xiaomi"
"ro.miui.enable_cloud_verify" = "true"
"ro.vendor.radio.build_region" = "cn"
"ro.vendor.radio.build_profile" = "miui"
